sudo: required
dist: trusty
addons:
  apt:
    packages:
    - texlive-latex-extra # we need this for all the latex package we use, recommended is not enough
    - texlive-generic-recommended # .. and more ...
    - latex-xcolor # ... and more latex packages
    - texlive-fonts-recommended # fonts...
    - cm-super # more fonts
    - texlive-xetex # latex to pdf converter

language: python
python:
  - "3.6"
install:
- wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb && sudo dpkg -i pandoc-1.19.1-1-amd64.deb
- pip install flit
- pip install jupyter_client
- flit install
# command to run tests
script: py.test
